version: "3"

services:
    backend:
        image: node:14
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 5000:5000
        environment:
            - PORT=5000
        command: sh -c "npm install && npm run dev"
